### ISSUE TITLE
Doesn't work with Firefox 34 on Android

### ISSUE THREAD

**Issue by kparal** [kevincox/youtube-e2l#10]
Hello, thanks for a great extension. It works correctly for me with Firefox 33 (stable) on Android. But it doesn't work with Firefox 34 (Beta) on Android. A regular YouTube object is shown, the extension doesn't seem to have any effect.

Can you please fix it? Thanks!

**Comment by AlexVallat** [comment]
I've attached a debugger, and it's throwing a "Component does not have requested interface" error. Some further investigation leads me to believe that this is almost certainly due to https://bugzilla.mozilla.org/show_bug.cgi?id=1107240 but I have no idea when or if that will get fixed.

According to one of the comments on the issue, it can be worked around by not using a contentStyleFile, which is not exactly a solution. I don't know if it's worth doing anything to try and fix this here, or if the best idea is to wait and see if Mozilla fix it on their end.

**Comment by kevincox** [comment]
This should be fixed by the pull request above.  It implements a workaround until firefox gets fixed.

**Comment by kparal** [comment]
Thank you. I'll be waiting for a new version on addons.mozilla.org.
